# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-SessionManager
version:      1.01
version_from: SessionManager.pm
installdirs:  site
requires:
    Apache::Session:               1.54
    mod_perl:                      1.24

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
